### ISSUE TITLE
[FEAT] MediaElch 2.12.0

### ISSUE THREAD

**Issue by chaosfreak93** [linuxserver/docker-mediaelch#3]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please update and support MediaElch 2.12.0

### Reason for change

A new version has been released

**Comment by thespad** [comment]
Their PPA builds failed (we use the Jammy package): https://launchpad.net/~mediaelch/+archive/ubuntu/mediaelch-stable/+packages

Once they're available we'll automatically build the new release
