### ISSUE TITLE
Please update MediaElch to 2.12.0

### ISSUE THREAD

**Issue by Rygle** [linuxserver/docker-mediaelch#4]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please update MediaElch to 2.12.0

### Reason for change

https://github.com/Komet/MediaElch/releases/tag/v2.12.0

**Comment by thelamer** [comment]
We ingest from their stable PPA, the package list has not been updated yet for Jammy: 
```
curl -sX GET http://ppa.launchpad.net/mediaelch/mediaelch-stable/ubuntu/dists/jammy/main/binary-amd64/Packages.gz | gunzip
```

Not sure why the package is published, it will ingest as soon as the PPA is updated.

**Comment by Rygle** [comment]
The ppa seems to have been updated.
https://launchpad.net/~mediaelch/+archive/ubuntu/mediaelch-stable

I don't even think any code needs to be changed, just the CI code run as it refers to the Ubuntu Jammy version which is the new version in the ppa.

**Comment by Rygle** [comment]
Added a pull request that might fix this issue by updating the package_versions.txt to match the latest stable version of mediaelch

https://github.com/linuxserver/docker-mediaelch/pull/5

**Comment by thelamer** [comment]
> Added a pull request that might fix this issue by updating the package_versions.txt to match the latest stable version of mediaelch
> 
> #5

That is not how it works, we still ingest from the PPA. Might be prudent to rebase to Noble, but that comes with it's own tradeoffs for compatibility of the image with hosts that have an old kernel. 

The noble repo returns the correct package: 

```
curl -sX GET http://ppa.launchpad.net/mediaelch/mediaelch-stable/ubuntu/dists/noble/main/binary-amd64/Packages.gz | gunzip
```

**Comment by thelamer** [comment]
The first step to getting this in is for you to test this image over your existing database and make sure it works: 

```
linuxserver/lsiodev-mediaelch
2.12.0.0-1-pkg-c0383d80-dev-83d12d761a5be4c59e703796dc1984d9e3e4cfd4
```
This is a noble rebase.

**Comment by Rygle** [comment]
Thank you @thelamer ;)

I am sorry but for no lack of trying I am unable to find that image. I have tried adding all sorts of host names to the start to try to pull it but no joy.

I am happy to test as soon as I can pull an image.

**Comment by thelamer** [comment]
My bad I forgot lsiodev is private on Dockerhub, here is the github link 

https://github.com/linuxserver/docker-mediaelch/pkgs/container/lsiodev-mediaelch/301440145?tag=2.12.0-noble-rebase

**Comment by Rygle** [comment]
OK, managed to pull - thanks!

Testing had slightly interesting results. All of these happened with an existing container and a new/fresh container, with or without browser add-ons (uBlock Origin, Firefox tracking protection, Privacy Badger, Decentralize, ForgetMeNot)

Most things seem to work OK at first, however the icons in the top row are missing (scrape, save, save all, rename, synchronize to Kodi, Export Database, reload, settings, about), also missing icons from Media Status Columns. This screenshot shows both issues, however as this was from a clean container it only has the first Media Status Column activated
![canvas2](https://github.com/user-attachments/assets/d1b186a7-7933-4ed7-b9c7-ecc1c3ef3959)


Experienced some hangs - see this screenshot
![canvas](https://github.com/user-attachments/assets/3fa963ad-e7c1-410b-8db5-b99f3eb5a2df)

Some hangs were briefly solved by reloading the tab/browser window, once it seemed to hang for a few minutes and a reload (stop/start) of the container fixed it, however I think after results below that waiting longer may have resolved this. Checked that all privacy related options were off, all things that might interfere, site data deleted. See above about extensions, privacy settings.

Additionally with the hangs when right-clicking to select the media status columns (press esc in Firefox to hide browser right-click menu), it would let me select and activate 1 column (with no icon), but subsequent attempts would not show the right click menu, which may be that the host end is hanging, or may be something else. Correction: after right clicking then waiting some time it allowed me to see the right-click menu from the container/app and select a second column

**Comment by Rygle** [comment]
Here are some logs obtained from Portainer - the libpng warnings may be related to icons (??)
`
MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.027 WARN  : QSqlQuery::prepare: database not open

MediaElch 2024-11-08 18:04:20.032 DEBUG : [Movies] Reloading took 2131 ms

MediaElch 2024-11-08 18:04:20.039 DEBUG : [MovieWidget] Changing movie to: "'71"

MediaElch 2024-11-08 18:04:20.102 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:20.102 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:20.103 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:20.107 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:20.107 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:20.109 WARN  : QPainter::begin: Paint device returned engine == 0, type: 2

MediaElch 2024-11-08 18:04:20.109 WARN  : QPainter::setCompositionMode: Painter not active

MediaElch 2024-11-08 18:04:20.109 WARN  : QPainter::setBrush: Painter not active

MediaElch 2024-11-08 18:04:20.109 WARN  : QPainter::setPen: Painter not active

MediaElch 2024-11-08 18:04:20.109 WARN  : QPainter::drawRects: Painter not active

MediaElch 2024-11-08 18:04:20.116 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:20.116 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:20.128 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:20.128 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:22.631 DEBUG : [MovieWidget] Changing movie to: "100 Bloody Acres"

MediaElch 2024-11-08 18:04:22.694 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:22.698 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:22.698 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:23.602 DEBUG : [MovieWidget] Changing movie to: "101 Dalmatians"

MediaElch 2024-11-08 18:04:23.666 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:23.667 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:23.673 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:23.673 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:23.679 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:23.679 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:24.810 DEBUG : [MovieWidget] Changing movie to: "11:14"

MediaElch 2024-11-08 18:04:24.881 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:24.881 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:26.060 DEBUG : [MovieWidget] Changing movie to: "12 Angry Men"

MediaElch 2024-11-08 18:04:26.126 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.127 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.127 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.128 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.128 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:26.129 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.129 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:26.135 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.135 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:26.147 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:26.148 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:26.802 DEBUG : [MovieWidget] Changing movie to: "12 Ordinary Men"

MediaElch 2024-11-08 18:04:27.597 DEBUG : [MovieWidget] Changing movie to: "13 Assassins"

MediaElch 2024-11-08 18:04:27.714 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:27.730 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:27.730 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:28.458 DEBUG : [MovieWidget] Changing movie to: "13 Minutes"

MediaElch 2024-11-08 18:04:31.052 DEBUG : [MovieWidget] Changing movie to: "13 Minutes"

MediaElch 2024-11-08 18:04:36.201 DEBUG : Using theme: "auto"

MediaElch 2024-11-08 18:04:36.202 WARN  : QPainter::begin: Paint device returned engine == 0, type: 2

MediaElch 2024-11-08 18:04:36.202 WARN  : QPainter::setCompositionMode: Painter not active

MediaElch 2024-11-08 18:04:36.202 WARN  : QPainter::setBrush: Painter not active

MediaElch 2024-11-08 18:04:36.202 WARN  : QPainter::setPen: Painter not active

MediaElch 2024-11-08 18:04:36.202 WARN  : QPainter::drawRects: Painter not active

MediaElch 2024-11-08 18:04:47.054 DEBUG : [MovieWidget] Changing movie to: "100 Bloody Acres"

MediaElch 2024-11-08 18:04:47.115 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:49.828 DEBUG : [MovieWidget] Changing movie to: "11:14"

MediaElch 2024-11-08 18:04:49.889 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:50.776 DEBUG : [MovieWidget] Changing movie to: "2001: A Space Odyssey"

MediaElch 2024-11-08 18:04:50.884 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:50.884 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:50.894 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:50.896 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:50.896 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:50.897 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:50.908 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:50.908 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:55.454 DEBUG : [MovieWidget] Changing movie to: "28 Days"

MediaElch 2024-11-08 18:04:55.538 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:55.548 INFO  : libpng warning: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:55.548 INFO  : libpng warning: profile matches sRGB but writing iCCP instead

MediaElch 2024-11-08 18:04:58.782 DEBUG : [MovieWidget] Changing movie to: "20th Century Women"

MediaElch 2024-11-08 18:04:59.879 DEBUG : [MovieWidget] Changing movie to: "2001: A Space Odyssey"

MediaElch 2024-11-08 18:04:59.944 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:59.944 INFO  : libpng warning: iCCP: known incorrect sRGB profile

MediaElch 2024-11-08 18:04:59.944 INFO  : libpng warning: iCCP: known incorrect sRGB profile`

**Comment by Rygle** [comment]
There is a bug report about the problem with the ppa and the Jammy build. Unfortunately unresolved but hopefully soon.

https://github.com/Komet/MediaElch/issues/1807

**Comment by Rygle** [comment]
The bug above is now closed.

`curl -sX GET http://ppa.launchpad.net/mediaelch/mediaelch-stable/ubuntu/dists/jammy/main/binary-amd64/Packages.gz | gunzip`

returns
`Version: 2.12.0.1-1~jammy`

The ppa and the docker image have been updated to 2.12.0 - I'm guessing the Noble rebase can come later.
